# Generated by Django 2.2.1 on 2019-05-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifdone', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_manage.Examination')),
            ],
        ),
    ]
