# Generated by Django 2.2.1 on 2019-05-28 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_manage', '0003_rectification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rectification',
            name='Problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_manage.Problem'),
        ),
    ]
