# Generated by Django 2.2.1 on 2019-05-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_manage', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Rectification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_manage.Rectification'),
        ),
    ]
