# Generated by Django 2.2.1 on 2019-05-29 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_manage', '0006_auto_20190529_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Rectification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_manage.Rectification'),
        ),
        migrations.AlterField(
            model_name='rectification',
            name='Problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_manage.Problem'),
        ),
    ]
