# Generated by Django 2.2.1 on 2019-05-30 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('safe_manage', '0007_auto_20190529_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='datecheck',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
