# Generated by Django 2.2.1 on 2019-06-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_manage', '0008_examination_datecheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_manage.Problem')),
            ],
        ),
    ]
